name: USOM IOC Sync

on:
  schedule:
    - cron: "0 */1 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Dependency Kur
        run: |
          pip install -r requirements.txt

      - name: Script Çalıştır
        run: |
          python usom_ioc_sync.py

      - name: Commit Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add output/*.xlsx

          git diff --cached --quiet || git commit -m "USOM IOC update"

          git push
